import Url from '../models/url';
import makeId from '../util/makeId';

export default (app) => {
  app.get('/db/seederbot', async(req, res, next) => {
    const urls = [
      {
        id: makeId(),
        rank: 1,
        path: 'http://facebook.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 2,
        path: 'http://twitter.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 3,
        path: 'http://google.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 4,
        path: 'http://youtube.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 5,
        path: 'http://instagram.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 6,
        path: 'http://linkedin.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 7,
        path: 'http://wordpress.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 8,
        path: 'http://pinterest.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 9,
        path: 'http://wikipedia.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 10,
        path: 'http://wordpress.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 11,
        path: 'http://blogspot.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 12,
        path: 'http://apple.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 13,
        path: 'http://adobe.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 14,
        path: 'http://tumblr.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 15,
        path: 'http://amazon.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 16,
        path: 'http://youtu.be/',
        description: '',
      },
      {
        id: makeId(),
        rank: 17,
        path: 'http://goo.gl/',
        description: '',
      },
      {
        id: makeId(),
        rank: 18,
        path: 'http://vimeo.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 19,
        path: 'http://flickr.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 20,
        path: 'http://microsoft.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 21,
        path: 'http://yahoo.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 22,
        path: 'http://bit.ly/',
        description: '',
      },
      {
        id: makeId(),
        rank: 23,
        path: 'http://godaddy.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 24,
        path: 'http://buydomains.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 25,
        path: 'http://vk.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 26,
        path: 'http://reddit.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 27,
        path: 'http://w3.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 28,
        path: 'http://nytimes.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 29,
        path: 'http://t.co/',
        description: '',
      },
      {
        id: makeId(),
        rank: 30,
        path: 'http://europa.eu/',
        description: '',
      },
      {
        id: makeId(),
        rank: 31,
        path: 'http://statcounter.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 32,
        path: 'http://weebly.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 33,
        path: 'http://blogger.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 34,
        path: 'http://soundcloud.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 35,
        path: 'http://github.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 36,
        path: 'http://bbc.co.uk/',
        description: '',
      },
      {
        id: makeId(),
        rank: 37,
        path: 'http://jimdo.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 38,
        path: 'http://qq.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 39,
        path: 'http://myspace.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 40,
        path: 'http://yandex.ru/',
        description: '',
      },
      {
        id: makeId(),
        rank: 41,
        path: 'http://wp.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 42,
        path: 'http://mozilla.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 43,
        path: 'http://google.de/',
        description: '',
      },
      {
        id: makeId(),
        rank: 44,
        path: 'http://gravatar.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 45,
        path: 'http://addthis.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 46,
        path: 'http://google.co.jp/',
        description: '',
      },
      {
        id: makeId(),
        rank: 47,
        path: 'http://theguardian.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 48,
        path: 'http://co.nz/',
        description: '',
      },
      {
        id: makeId(),
        rank: 49,
        path: 'http://bluehost.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 50,
        path: 'http://cnn.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 51,
        path: 'http://wix.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 52,
        path: 'http://nih.gov/',
        description: '',
      },
      {
        id: makeId(),
        rank: 53,
        path: 'http://paypal.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 54,
        path: 'http://stumbleupon.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 55,
        path: 'http://creativecommons.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 56,
        path: 'http://digg.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 57,
        path: 'http://huffingtonpost.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 58,
        path: 'http://issuu.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 59,
        path: 'http://feedburner.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 60,
        path: 'http://imdb.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 61,
        path: 'http://yelp.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 62,
        path: 'http://parallels.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 63,
        path: 'http://addtoany.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 64,
        path: 'http://google.co.uk/',
        description: '',
      },
      {
        id: makeId(),
        rank: 65,
        path: 'http://dropbox.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 66,
        path: 'http://amazonaws.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 67,
        path: 'http://forbes.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 68,
        path: 'http://baidu.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 69,
        path: 'http://go.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 70,
        path: 'http://washingtonpost.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 71,
        path: 'http://msn.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 72,
        path: 'http://slideshare.net/',
        description: '',
      },
      {
        id: makeId(),
        rank: 73,
        path: 'http://wixsite.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 74,
        path: 'http://wsj.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 75,
        path: 'http://etsy.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 76,
        path: 'http://eventbrite.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 77,
        path: 'http://ameblo.jp/',
        description: '',
      },
      {
        id: makeId(),
        rank: 78,
        path: 'http://archive.org/',
        description: '',
      },
      {
        id: makeId(),
        rank: 79,
        path: 'http://telegraph.co.uk/',
        description: '',
      },
      {
        id: makeId(),
        rank: 80,
        path: 'http://amazon.co.uk/',
        description: '',
      },
      {
        id: makeId(),
        rank: 81,
        path: 'http://fc2.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 82,
        path: 'http://sourceforge.net/',
        description: '',
      },
      {
        id: makeId(),
        rank: 83,
        path: 'http://mail.ru/',
        description: '',
      },
      {
        id: makeId(),
        rank: 84,
        path: 'http://e-recht24.de/',
        description: '',
      },
      {
        id: makeId(),
        rank: 85,
        path: 'http://ebay.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 86,
        path: 'http://cpanel.net/',
        description: '',
      },
      {
        id: makeId(),
        rank: 87,
        path: 'http://free.fr/',
        description: '',
      },
      {
        id: makeId(),
        rank: 88,
        path: 'http://doubleclick.net/',
        description: '',
      },
      {
        id: makeId(),
        rank: 89,
        path: 'http://livejournal.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 90,
        path: 'http://reuters.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 91,
        path: 'http://typepad.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 92,
        path: 'http://dailymail.co.uk/',
        description: '',
      },
      {
        id: makeId(),
        rank: 93,
        path: 'http://bloomberg.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 94,
        path: 'http://cpanel.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 95,
        path: 'http://yahoo.co.jp/',
        description: '',
      },
      {
        id: makeId(),
        rank: 96,
        path: 'http://about.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 97,
        path: 'http://macromedia.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 98,
        path: 'http://amzn.to/',
        description: '',
      },
      {
        id: makeId(),
        rank: 99,
        path: 'http://eepurl.com/',
        description: '',
      },
      {
        id: makeId(),
        rank: 100,
        path: 'http://wikimedia.org/',
        description: '',
      },
    ];

    for (let i = 0; i < urls.length; i++) {
      const newUrl = new Url(urls[i]);
      newUrl.save();
    }

    res.send('Database seeded!');
  });
};
